### ISSUE TITLE
Outdated devDependency package versions

### ISSUE THREAD

**Issue by akwright** [corysimmons/sip-of-jeet#1]
Hi Cory,

The package.json file has outdated dependencies for the packages.
If you replace all the hard-coded versions with *, that will fix the issue.
The one that's breaking when you clone the repo, run `npm install`, and then `gulp` is the browser-sync dependency.

Thanks!

**Comment by corysimmons** [comment]
I'll update them but I don't think updating them to `*` is ever a good idea since packages might upgrade to breaking changes and cause things to break hard.

**Comment by akwright** [comment]
Oh, that's a good thought. I'm pretty new to gulp and task runners in general, so that's good to know.
Appreciate all that you have done with Jeet! Really love it.

**Comment by corysimmons** [comment]
If you like Jeet you should *really* check out my new grid system [Lost](https://github.com/corysimmons/lost). It's a lot better than any grid out there right now.

**Comment by akwright** [comment]
Oh man, it uses PostCSS? Yeah, definitely checking it out. Thanks!

**Comment by corysimmons** [comment]
Yeah, offers a ton of features. Thanks for your interest in my work. =)

Also, fixed this. Closing.
