### ISSUE TITLE
Sip of Lost

### ISSUE THREAD

**Issue by dbox** [corysimmons/sip-of-jeet#2]
Do you have something similar, but with Lost and stylus? trying to set it up myself now but not super familiar with gulp..

**Comment by corysimmons** [comment]
Sure https://github.com/corysimmons/lost/blob/gh-pages/gulpfile.js

I also have something for Sass https://github.com/corysimmons/lost-sass-gulp

It's all just about using Stylus in your pipeline THEN using PostCSS/Lost.

Lemme know if you have any questions and send me a really dumbed down gulpfile and I'll help you debug it if you run into trouble. =)

**Comment by dbox** [comment]
Thanks!

**Comment by corysimmons** [comment]
De nada. Gimme 2 secs and I'll make a *super* simple gulpfile for ya.

**Comment by dbox** [comment]
Before you replied I found the last stylus version and have been messing
around with it. Seems pretty stable ...

**Comment by corysimmons** [comment]
Update Stylus to the latest `npm i -g stylus` to make sure Lost's settings work just fine. Then...

`package.json`
```js
{
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-postcss": "^5.1.6",
    "gulp-stylus": "^2.0.2",
    "lost": "^6.2.0"
  }
}
```

`gulpfile.js`
```js
var gulp = require('gulp'),
    stylus = require('gulp-stylus'),
    postcss = require('gulp-postcss'),
    lost = require('lost');

gulp.task('styles', function() {
  return gulp.src('src/**/*.styl')
    .pipe(stylus())
    .pipe(postcss([
      lost()
    ]))
    .pipe(gulp.dest('dest/'));
});

gulp.watch('src/**/*.*', ['styles']);

gulp.task('default', ['styles']);
```

**Comment by corysimmons** [comment]
This will watch Stylus files in the `src/` dir, run Lost on them, and output them to the `dest/` dir.

This is about as simple as a gulpfile gets. Lemme know if you have any questions about Gulp in general (as I like it).

**Comment by corysimmons** [comment]
So far as using the Stylus version of Lost. I highly recommend you jump on the Gulp bandwagon. There's tons of stuff you can do with Gulp/Grunt/pure-npm that other workflows just can't offer. It's a huge upgrade in your frontend development workflow.

But if you're gonna keep using the Stylus version I think the last stable version of Lost in Stylus was 5.1.5, but I'm not offering support for it anymore so yeah, jump on the latest version and if you need any help I'll be glad to help you out.

**Comment by dbox** [comment]
Yeah I'm starting to get into it,, especially browser sync - so fast!. I
really like roots too, but wasn't sure how to integrate postcss with it.

**Comment by dbox** [comment]
I was brought onto a gulp/stylus/jeet project last October and it changed
my life. Never looked back.

**Comment by corysimmons** [comment]
Yeah I'm a big fan of Browser Sync + Gulp + Stylus + Lost.

I'm not sure how friendly Roots is with PostCSS. @jenius chime in?

**Comment by dbox** [comment]
Yeah, you two basically single-handedly have made the most beautiful
front-end workflows:

Roots / Stylus / jeet (maybe Lost now) / axis / rupture

(I've been helping with some Axis additions lately, too. )

Love it!

Hardest part is trying to convince 2 team members who love SCSS and
brackets. :) it's a never-ending battle

**Comment by corysimmons** [comment]
I didn't make Roots, Stylus, Axis, or Rupture. :)

@jenius made Roots, Axis, and Rupture, and TJ made Stylus.

I just do grids bro. :)

**Comment by dbox** [comment]
Oh I know. I'm just lumping you in because of how much of a workflow game
changer the grids are for me, and how seamless it is with jenius's tools.

**Comment by dbox** [comment]
Plus, I think the term grid doesn't even really give it enough credit to
what it really is, especially combined with the responsive aspect.

I basically build all sites with one breakpoint now: above or below 767px .
And if built super fluidly, it's really all you need.

**Comment by corysimmons** [comment]
haha, thanks glad you like 'em. =)

**Comment by jenius** [comment]
Sorry for the late response, but yup [accord supports postcss](https://github.com/jenius/accord/blob/master/docs/postcss.md), next roots update you will be able to simply install `postcss` using npm and it will automatically transform any `.css` files :grinning:
